modLoader = "javafml"
loaderVersion = "[1,)"
license = "MPL-2.0"

[[mods]]
modId = "buildcraft"
version = "${version}"
displayName = "BuildCraft"
authors = "SpaceToad, the BuildCraft team, Cyndi's MC Mods"
description = '''
Pipes, engines, quarries and automation.
'''

[[dependencies.buildcraft]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.buildcraft]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
